### PR TITLE
Added Hydrate overview to README.md, fixed gitignore

### LINKED ISSUE #7: As a user, I expect to see information about the Hydrate extension on the project's default Github page
Create a README file that describes project hydrate and how this extension will work with project hydrate and more details about how to build it, deploy it, test it and run it.

### PR DESCRIPTION
**Pull request by madelineliao**
Closes #7 

Updated the README with a description of the Hydrate extension and links to its dependencies and edited `.gitignore` to ignore `out/*`.

### CODE REVIEW

**Comment by andrebriggs** [comment]
@madelineliao looks like there are additional changes in this PR. It would be good to update your PR description to list them out

**Comment by andrebriggs** [comment]
@madelineliao did we mean to check in the `out/*` files?

**Comment by andrebriggs** [comment]
@madelineliao describing the changes in `src/extension.ts` would be useful to reviewers

**Comment by madelineliao** [comment]
> @madelineliao looks like there are additional changes in this PR. It would be good to update your PR description to list them out



> @madelineliao did we mean to check in the `out/*` files?

I didn't sync my fork with the microsoft:master branch after the first pull request which caused this. Fixing now.

**Comment by samiyaakhtar** [comment]
Preferably, it's nice to have a single PR only close a single issue :) Does this one actually include the part about adding this extension under the Kubernetes extension?

**Pull request merged**
